<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_textKulID</name>
   <tag></tag>
   <elementGuidId>59005223-ca9e-4a52-97f1-7eee6c301c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textKulID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textKulID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eac8ea2c-e3db-4fd0-90d9-a9f0f8e4a139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textKulID</value>
      <webElementGuid>288f23ca-950d-4114-9916-7a31355d85cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfc3c616-b58d-46d8-ba91-7f8d3be67b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b7533335-b9f4-4f0a-9955-e99a1e039925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textKulID</value>
      <webElementGuid>d0d54c7c-571b-4fda-8cc3-7964ecfcbbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>0926503002 şeklinde giriniz</value>
      <webElementGuid>a946f66c-d373-4a7b-8b5c-640b5b6e2495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.style.backgroundColor='White'; this.style.color = 'Black';</value>
      <webElementGuid>eb1e5562-ace3-4c44-87a6-7c3b08bf18b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.style.backgroundColor='#E0F7FA'; this.style.color='Black';</value>
      <webElementGuid>baf07575-e9db-4c43-871e-b3182b04ee93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textKulID&quot;)</value>
      <webElementGuid>2c100299-8223-4e85-b0dd-de44ad70bd08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textKulID']</value>
      <webElementGuid>5e0639a4-c0f8-41b9-a6c7-cc82ffa464f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table[2]/tbody/tr[2]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>0c7e1c20-0d07-48f2-ba6c-1146524c5b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>fc0d261b-504a-42d2-90e6-290f7786aeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'textKulID' and @type = 'text' and @id = 'textKulID' and @title = '0926503002 şeklinde giriniz']</value>
      <webElementGuid>6ac66cdb-3b06-42a5-ae03-f1520463b437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
