<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_textSifre</name>
   <tag></tag>
   <elementGuidId>c27c53fe-02af-4a60-bf80-e28cf34095e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textSifre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textSifre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df06c03f-daac-4abd-b297-d15c7881f533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textSifre</value>
      <webElementGuid>3e66cc84-515e-478f-9ae7-4e57fd90f5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f58fb9f3-efff-4fe6-9ab3-e00fe0087c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textSifre</value>
      <webElementGuid>3a2fd7dc-b223-467b-bee5-f8b4e6d60e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.style.backgroundColor='White'; this.style.color = 'Black';</value>
      <webElementGuid>8fceef84-2b90-4640-918b-b00d1fb491e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.style.backgroundColor='#E0F7FA'; this.style.color='Black';</value>
      <webElementGuid>d64b4679-2eea-4920-a36b-77b1ce4e6a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textSifre&quot;)</value>
      <webElementGuid>523bbd3c-93f4-4ecb-9928-6e81b7392a22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textSifre']</value>
      <webElementGuid>f260332d-50b4-4d71-ab80-201c31032ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table[2]/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>287c89f3-0feb-49fa-8e61-35d0667d9e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>1c7430c6-f31a-41c7-915d-d97321deaa23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'textSifre' and @type = 'password' and @id = 'textSifre']</value>
      <webElementGuid>65780484-a4a4-4cb1-9039-2304b5cd5734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
