<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_buttonTamam</name>
   <tag></tag>
   <elementGuidId>966b570a-3935-4637-9a5e-ad945410ff51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonTamam</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buttonTamam']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94e87258-c06c-4a58-8ede-e1b64db36fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>790b6750-e0bc-4f75-a047-f58ed7fc4281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buttonTamam</value>
      <webElementGuid>4700e602-32d7-497b-837a-1ea4042c0793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Giriş</value>
      <webElementGuid>1a25745c-743e-440b-aff4-19bb54c3f107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;buttonTamam&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>93706a6b-e2a7-49f3-8791-c4270118b86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonTamam</value>
      <webElementGuid>3903033b-ff9b-466f-9be3-749a55307187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonTamam&quot;)</value>
      <webElementGuid>19db04ea-c0bd-46c7-afad-cac6ea41233b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buttonTamam']</value>
      <webElementGuid>035e8807-2aed-4115-b7bb-dc9198686e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table[2]/tbody/tr[2]/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>3cea997f-0de4-4466-a2c6-003c99984dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>4ac19663-dda4-4559-aac0-df9589e4b915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'buttonTamam' and @id = 'buttonTamam']</value>
      <webElementGuid>9192897d-883d-41c0-90b9-0a9d2bd52a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
